### ISSUE TITLE
break-before/after not working correctly in some cases (was: Pagination support?)

### ISSUE THREAD

**Issue by zopyx** [Trimmarks/versatype-issues#21]
Is there any kind of pagination support? The documentation say NO for all variants of page-break-XXX?

**Comment by kwkbtr** [comment]
Vivliostyle supports `page-break-*` properties.
(Properties listed in http://vivliostyle.com/en/documentation/supported-features/ are _supported properties_)
_"Depends on browser's capability: No"_ means that the feature does not depend on whether the used browser (Google Chrome in the case of Vivliostyle Formatter) supports it since we implement the feature on our own.

**Comment by frivoal** [comment]
@zopyx Thanks for highlighting that the documentation is unclear. We will rephrase to make it clearer.

**Comment by zopyx** [comment]
Pagination does not seem to work correctly in all cases:

No pagination:
https://www.print-css.rocks/lesson-css-transformations.html

Pagination working:

https://www.print-css.rocks/lesson-pagination.html

**Comment by kwkbtr** [comment]
The not working case is probably a bug. We will investigate it.

**Comment by kwkbtr** [comment]
Fixed in 2016.4 release.
